include:
  - project: piveau/misc/gitlab-ci-templates
    file:
      - /templates/.gitlab-ci-publish-template.yml

cache:
  paths:
   - node_modules/

stages:
  - build
  - publish
  - publish sources

build-asset:
  stage: build
  image: node:16-alpine3.16
  only:
    - master
    - merge_requests
  script:
    - npm install
    - npm run build

publish package to npm repository:
  stage: publish
  image: node:16-alpine3.16
  only:
    - tags
  script:
    - echo -e "\n//paca.fokus.fraunhofer.de/repository/npm-hosted/:_authToken=${NPM_TOKEN}" >> .npmrc
    - npm install
    - if [[ "$CI_COMMIT_TAG" == v* ]]; then npm run ci-publish $CI_COMMIT_TAG; fi
    - if [[ "$CI_COMMIT_TAG" == *@* ]]; then npm run ci-publish $CI_COMMIT_TAG; fi

publish to gitlab.com DEU dataeuropa:
  stage: publish
  image: ubuntu:20.04
  allow_failure: true
  only:
    refs:
      - master

  tags:
    - vst
  script:
    - apt-get update
    - apt-get install -y git python3-pip python3-dev
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - ln -s /usr/bin/python3 /usr/local/bin/python
    - pip3 install --upgrade pip
    - pip3 install git-filter-repo
    - git remote update
    - git fetch 
    - git checkout --track origin/master
    - git filter-repo --invert-paths --force --path .gitlab-ci.yml
    - git clone https://$GITLAB_COM_USERNAME:$GITLAB_COM_TOKEN@gitlab.com/dataeuropa/utilities/ui-modules target-repo
    - cd target-repo
    - git remote add modified-source ..
    - git pull modified-source master --allow-unrelated-histories --tags --force
    - git push origin master --tags --force
