#cache:
#  paths:
#   - node_modules/

stages:
  - build
  - publish

build-asset:
  stage: build
  #image: node:lts-alpine3.10
  image: node:16-alpine3.16
  only:
    - master
    - next
    - beta
    - develop
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

publish package to npm repository:
  stage: publish
  image: node:lts-buster-slim
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install --only=dev
  only:
    refs:
      #- master
      #- next
      #- beta
      - develop
    changes:
      - package.json

  script:
    # - echo npm run semantic-release
    - export VERSION=$(node -p "require('./package.json').version")
    - export CONTAINER_RELEASE_IMAGE=$CI_REGISTRY_IMAGE:$VERSION
    - echo $CONTAINER_RELEASE_IMAGE
    - echo npm run deploy
