cache:
  paths:
   - node_modules/

stages:
  - build
  - publish

build-asset:
  stage: build
  image: node:16-alpine3.16
  tags:
    - fokus-runner
  only:
    - master
    - merge_requests
  script:
    - npm install
    - npm run build

publish package to npm repository:
  stage: publish
  image: node:16-alpine3.16
  tags:
    - fokus-runner
  only:
    - tags
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_REGISTRY_TOKEN}" > .npmrc
    - npm install
    - if [[ "$CI_COMMIT_TAG" == v* ]]; then npm run ci-publish $CI_COMMIT_TAG; fi
    - if [[ "$CI_COMMIT_TAG" == *@* ]]; then npm run ci-publish $CI_COMMIT_TAG; fi