cache:
  paths:
   - node_modules/

stages:
  - build
  - publish

build-asset:
  stage: build
  #image: node:lts-alpine3.10
  image: node:16-alpine3.16
  only:
    - master
    - develop
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

publish package to npm repository:
  stage: publish
  #image: node:16-alpine3.16
  image: node:lts-buster-slim
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install --only=dev
  only:
    refs:
      - master
      - develop
#    changes:
#      - package.json
  script:
    - export VERSION=$(node -p "require('./package.json').version")
    - echo deploy VERSION $VERSION
    #- npm run deploy
    - npm run semantic-release --dry-run
