cache:
  paths:
   - node_modules/

stages:
  - build
  - publish

build-asset:
  stage: build
  image: node:16-alpine3.16
  only:
    - master
    - merge_requests
  script:
    - npm ci
    - npm run build

publish package to npm repository:
  stage: publish
  image: node:16-alpine3.16
  rules:
    - if: '$CI_COMMIT_TAG' =~ /^v/'
      when: always
  script:
    - echo "//paca.fokus.fraunhofer.de/repository/npm-hosted/:_authToken=${NPM_TOKEN}" >> .npmrc
    - npm ci
    - npm run ci-publish $CI_COMMIT_TAG

# publish to gitlab.com:
#   stage: publish
#   image: appropriate/curl
#   only:
#     - master
#   script:
#     # Publish code to GitLab.com
#     - curl -X POST -F token=$PIVEAU_PUBLISH_TOKEN -F ref=master -F "variables[VAR_PROJECT_PATH]=$CI_PROJECT_PATH " -F "variables[VAR_PROJECT_NAME]=$CI_PROJECT_NAME" https://gitlab.fokus.fraunhofer.de/api/v4/projects/9624/trigger/pipeline