include:
  - project: piveau/misc/gitlab-ci-templates
    file:
      - /templates/.gitlab-ci-publish-template.yml

cache:
  paths:
   - node_modules/

stages:
  - build
  - publish
  - publish sources

build-asset:
  stage: build
  image: node:16-alpine3.16
  only:
    - master
    - merge_requests
  script:
    - npm ci
    - npm run build

publish package to npm repository:
  stage: publish 
  image: node:16-alpine3.16
  only:
    - tags
  script:
    - echo -e "\n//paca.fokus.fraunhofer.de/repository/npm-hosted/:_authToken=${NPM_TOKEN}" >> .npmrc
    - npm ci
    - if [[ "$CI_COMMIT_TAG" == v* ]]; then npm run ci-publish $CI_COMMIT_TAG; fi
    - if [[ "$CI_COMMIT_TAG" == *@* ]]; then npm run ci-publish $CI_COMMIT_TAG; fi


publish sources to GITLAB.COM:
  stage: publish sources
  image: ubuntu:20.04
  allow_failure: true
  only:
    refs:
      - master

  tags:
    - vst
  script:
    - echo "publish sources to GITLAB.COM"
    - apt-get update
    - apt-get install -y git python3-pip python3-dev
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - ln -s /usr/bin/python3 /usr/local/bin/python
    - pip3 install --upgrade pip
    - pip3 install git-filter-repo
    - git clone https://$GITLAB_USER:$GITLAB_TOKEN@$CI_SERVER_HOST/piveau/ui/$SERVICE_NAME.git
    - cd $SERVICE_NAME
    - git checkout master
    - \cp $CI_PROJECT_DIR/LICENSE.md .
    - git commit -am 'add DEU license'
    - git filter-repo --invert-paths --force --path .gitlab-ci.yml
    - cd ..
    - git clone https://$GITLAB_COM_USER:$GITLAB_COM_TOKEN@$GITLAB_COM_REPO/utilities/ui-modules target
    - cd target
    - git remote add modified-source ../$SERVICE_NAME
    - git pull modified-source master --allow-unrelated-histories --tags
    - git push origin master --tags


 
