version: '3.3'
services:
    hub-ui-theme-builder:
        image: 'dockerhub.fokus.fraunhofer.de:5000/piveau/hub/theme-builder:latest'
        volumes:
            - 'src:/App/src'
            - 'public:/App/public'
            - 'html:/usr/share/nginx/html/'
        restart: "no"
        deploy:
          restart_policy:
            condition: on-failure
            max_attempts: 3
        logging:
            options:
                max-size: 1g
        environment:
          - VUE_APP_METADATA_TITLE=My dataportal

    hub-ui-theme-server:
        image: 'dockerhub.fokus.fraunhofer.de:5000/piveau/hub/piveau-hub-ui:latest'
        ports:
            - '17080:8080'
        volumes:
            - 'html:/usr/share/nginx/html/'
        command: /bin/sh -c "chmod a+rw /usr/share/nginx/html/js && chmod a+rw /usr/share/nginx/html/js/* && /runtimeconfig.sh"
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
          - VUE_APP_METADATA_TITLE=My dataportal

volumes:
  html:
  src:
  public:
