version: '3.3'
services:

    # To start an container where you can develop your own theme and see changes instantly, uncomment the followging lines.
    # A piveau hub-ui instance will be launched at localhost:17085
    # Please note that the folders src and public should contain a "theme"

    hub-ui-theme-dev:
        image: 'registry.gitlab.com/piveau/hub/piveau-hub-ui/theme-builder:latest'
        volumes:
            - './src:/App/src'
            - './public:/App/public'
        restart: "no"
        # command: /bin/sh -c "cd /App && cp -a src original_src && npm --silent ci && cp config/user-config.sample.js config/user-config.js && npm run serve"
        command: /bin/sh -c "cd /App && vars=$$(env | grep VUE_ | sed -e 's/^/\$$/') && cp config/runtime-config.js config/runtime-config.tmp && envsubst < config/runtime-config.tmp > config/runtime-config.js && rm config/runtime-config.tmp && npm --silent ci && cp config/user-config.sample.js config/user-config.js && npm run serve"
        ports:
            - '17085:8080'
        deploy:
          restart_policy:
            condition: on-failure
            max_attempts: 3
        logging:
            options:
                max-size: 1g
