cache:
  paths:
   - node_modules/

stages:
  - build
  - publish


build-asset:
  stage: build
  image: node:16-alpine3.16
  only:
    - master
    - next
    - merge_requests
  script:
    - npm ci
    - npm run link-module
    - npm run build
  artifacts:
    paths:
      - dist

publish package to npm repository:
  stage: publish
  image: node:lts-buster-slim
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install --only=dev
  only:
    refs:
      - master
      - next
  script:
    - npm run semantic-release

publish to gitlab.com:
  stage: publish
  image: appropriate/curl
  only:
    - master
  script:
    # Publish code to GitLab.com
    - curl -X POST -F token=$PIVEAU_PUBLISH_TOKEN -F ref=master -F "variables[VAR_PROJECT_PATH]=$CI_PROJECT_PATH " -F "variables[VAR_PROJECT_NAME]=$CI_PROJECT_NAME" https://gitlab.fokus.fraunhofer.de/api/v4/projects/9624/trigger/pipeline


