// List of all DGs
const dgs = [
  'Eurostat',
  'Directorate-General for Communication',
  'Directorate-General for Competition',
  'Directorate-General for Education, Youth, Sport and Culture',
  'Directorate-General for European Civil Protection and Humanitarian Aid Operations (ECHO)',
  'Directorate-General for Budget',
  'Directorate-General for Maritime Affairs and Fisheries',
  'Directorate-General for Justice and Consumers',
  'Directorate-General for Informatics',
  'Directorate-General for Health and Food Safety',
  'Directorate-General for Agriculture and Rural Development',
  'Directorate-General for Research and Innovation',
  'Directorate-General for Financial Stability, Financial Services and Capital Markets Union',
  'Joint Research Centre',
  'Directorate-General for Structural Reform Support',
  'Directorate-General for Defence Industry and Space',
  'Directorate-General for Environment',
  'Directorate-General for Climate Action',
  'Directorate-General for Regional and Urban Policy',
  'Directorate-General for Employment, Social Affairs and Inclusion',
  'Directorate-General for Trade',
  'Directorate-General for Energy',
  'Directorate-General for International Partnerships',
  'Directorate-General for Neighbourhood and Enlargement Negotiations',
  'Directorate-General for Migration and Home Affairs',
  'Directorate-General for Economic and Financial Affairs',
  'Directorate-General for Internal Market, Industry, Entrepreneurship and SMEs',
  'Directorate-General for Mobility and Transport',
  'Directorate-General for Interpretation',
  'Directorate-General for Human Resources and Security',
  'Directorate-General for Communications Networks, Content and Technology',
  'Directorate-General for Taxation and Customs Union',
  'Directorate-General for Translation',
];

export default dgs;
